name: VPS Sync via Tmate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours

jobs:
  vps-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start Tmate session
        uses: mxschmitt/action-tmate@v3
        id: tmate

      - name: Switch to or create 'vps-data' branch
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          if git ls-remote --heads origin vps-data; then
            git checkout vps-data
            git pull origin vps-data
          else
            git checkout -b vps-data
          fi

      - name: Restore existing VPS data
        run: |
          if [ -d vps_data ]; then
            echo "Found existing VPS data."
          else
            mkdir vps_data
            echo "No data found, created vps_data folder."
          fi

      - name: Run your VPS setup
        run: |
          echo "Example VPS data" > vps_data/example.txt

      - name: Commit and push updated data
        run: |
          git add vps_data
          git commit -m "Update VPS data at $(date -Is)" || echo "No changes to commit"
          git push origin vps-data
