      - name: Start tmate in background and print SSH once
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate jq

          # Start tmate in background
          tmate -S /tmp/tmate.sock new-session -d

          # Wait for it to generate connection info
          sleep 2

          # Show SSH session URL only once
          SSH_SESSION=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "SSH Session: $SSH_SESSION"

          # Optional: sleep for 5h 30m before job ends
          sleep 19800
