name: VPS Sync via Tmate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # runs hourly, for example

jobs:
  vps-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push new branch later

      - name: Start Tmate session
        uses: mxschmitt/action-tmate@v4
        id: tmate
        # Optional: expose port if required

      - name: Switch to or create 'vps-data' branch
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          if git ls-remote --heads origin vps-data; then
            git checkout vps-data
            git pull origin vps-data
          else
            git checkout -b vps-data
          fi

      - name: Fetch Existing VPS Data
        run: |
          if [ -f vps_data.json ]; then
            echo "Found existing data:"
            cat vps_data.json
          else
            echo "No existing data found."
          fi

      - name: Run VPS Data Collection Script
        run: |
          # Replace with your actual data-gathering commands
          echo "{\"timestamp\":\"$(date -Is)\",\"info\":\"my vps data\"}" > vps_data.json

      - name: Commit and push updated data
        run: |
          git add vps_data.json
          git commit -m "Update VPS data at $(date -Is)" || echo "No changes to commit"
          git push origin vps-data
